image: openjdk:11

variables:
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  ANDROID_HOME:      "$CI_PROJECT_DIR/android-sdk"
  GRADLE_USER_HOME:  "$CI_PROJECT_DIR/.gradle"

# Кэшируем только Gradle
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/

stages:
  - setup
  - build
  - test

setup_sdk:
  stage: setup
  script:
    # Утилиты для скачивания SDK
    - apt-get update -qq && apt-get install -y -qq wget unzip

    # Создаём папки под command-line tools
    - mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"

    # Скачиваем и распаковываем
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
    - unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/latest"
    - rm cmdline-tools.zip

    # Добавляем в PATH
    - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"

    # Принимаем лицензии и ставим нужные пакеты
    - yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
    - sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    # Для отладки: покажем, что лежит в папке
    - ls -R "$ANDROID_SDK_ROOT"

  artifacts:
    expire_in: 1h
    paths:
      - android-sdk/

build:
  stage: build
  dependencies:
    - setup_sdk
  before_script:
    - export ANDROID_SDK_ROOT="$CI_PROJECT_DIR/android-sdk"
    - export ANDROID_HOME="$CI_PROJECT_DIR/android-sdk"
    - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
  script:
    - ./gradlew assembleDebug --no-daemon
  artifacts:
    expire_in: 1h
    paths:
      - app/build/outputs/apk/debug/*.apk

test:
  stage: test
  dependencies:
    - setup_sdk
  before_script:
    - export ANDROID_SDK_ROOT="$CI_PROJECT_DIR/android-sdk"
    - export ANDROID_HOME="$CI_PROJECT_DIR/android-sdk"
    - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
  script:
    - ./gradlew testDebugUnitTest jacocoTestReport --no-daemon
  artifacts:
    expire_in: 1h
    reports:
      junit: app/build/test-results/testDebugUnitTest/*.xml
    paths:
      - app/build/reports/jacoco/
