image: registry.gitlab.com/developmentseed/docker-android-sdk:33

stages:
  - build
  - test

before_script:
  - yes | sdkmanager --licenses
  - sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

build:
  stage: build
  script:
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/
    paths:
      - app/build/reports/tests/testDebugUnitTest/
    expire_in: 1 week
