image: eclipse-temurin:17-jdk-jammy

stages:
  - build
  - test

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_TOOLS: "9477386"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # 1) Системные утилиты
  - apt-get update -yq && apt-get install -yq wget unzip

  # 2) Подготовка папки для SDK
  - export ANDROID_HOME="$PWD/android-sdk-root" && mkdir -p "$ANDROID_HOME/cmdline-tools/latest"

  # 3) Скачиваем и сразу распаковываем в latest
  - wget -qO sdk.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip"
  - unzip -qq sdk.zip -d "$ANDROID_HOME/cmdline-tools/latest"

  # 4) Добавляем sdkmanager в PATH
  - export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"

  # 5) Принимаем лицензии и ставим платформы
  - yes | sdkmanager --licenses >/dev/null
  - sdkmanager "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}"

  # 6) Делаем gradlew исполняемым
  - chmod +x ./gradlew

buildDebug:
  stage: build
  script:
    - echo "Собираем debug-APK…"
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unitTest:
  stage: test
  needs:
    - buildDebug
  script:
    - echo "Запускаем unit-тесты…"
    - ./gradlew testDebugUnitTest
