image: openjdk:11

variables:
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/
    - android-sdk/

stages:
  - setup
  - build
  - test

setup_sdk:
  stage: setup
  script:
    - apt-get update -qq && apt-get install -y -qq wget unzip
    - mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
    - unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
    - rm cmdline-tools.zip
    - yes | "$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses
    - "$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2"
  artifacts:
    paths:
      - android-sdk/

build:
  stage: build
  script:
    - ./gradlew assembleDebug --no-daemon
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk

test:
  stage: test
  script:
    - ./gradlew testDebugUnitTest jacocoTestReport --no-daemon
  artifacts:
    reports:
      junit: app/build/test-results/testDebugUnitTest/*.xml
    paths:
      - app/build/reports/jacoco/
