stages:
  - build
  - test

# Кеширование ускоряет сборку (Gradle-кеш, зависимости)
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/
    - build/

# Используем образ с Android SDK и JDK (лучше выбрать конкретную версию)
image: registry.gitlab.com/haynes/android-docker/android-31:latest

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew  # Даем права на исполнение gradle-wrapper

build:
  stage: build
  script:
    - ./gradlew assembleDebug  # Собираем debug-версию
  artifacts:
    paths:
      - app/build/outputs/apk/debug/  # Сохраняем собранный APK

test:
  stage: test
  script:
    - ./gradlew test  # Запускаем unit-тесты
    # Если есть инструментальные тесты (AndroidTest):
    # - ./gradlew connectedAndroidTest
  artifacts:
    reports:
      junit:
        - app/build/test-results/**/*.xml  # Отчеты тестов