image: eclipse-temurin:17-jdk-jammy

stages:
  - build
  - test

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_TOOLS: "9477386"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # 1. Утилиты
  - apt-get update -yq && apt-get install -yq wget unzip

  # 2. Папка для SDK
  - export ANDROID_HOME="$PWD/android-sdk-root"
  - export ANDROID_SDK_ROOT="$ANDROID_HOME"
  - mkdir -p "$ANDROID_HOME/cmdline-tools"

  # 3. Скачиваем и распаковываем
  - wget -qO sdk.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip"
  - unzip -qq sdk.zip -d /tmp
  - mv /tmp/cmdline-tools "$ANDROID_HOME/cmdline-tools/latest"
  - rm -rf sdk.zip /tmp/cmdline-tools

  # 4. Включаем sdkmanager в PATH
  - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

  # 5. Отладка (можно убрать после успешного прогона)
  - ls -R "$ANDROID_HOME/cmdline-tools"
  - which sdkmanager && sdkmanager --version

  # 6. Принимаем лицензии и устанавливаем пакеты
  - yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
  - sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}"

  # 7. Проверяем gradlew
  - chmod +x ./gradlew




buildDebug:
  stage: build
  script:
    - echo "Собираем debug-APK…"
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unitTest:
  stage: test
  needs:
    - buildDebug
  script:
    - echo "Запускаем unit-тесты…"
    - ./gradlew testDebugUnitTest
