image: eclipse-temurin:17-jdk-jammy

stages:
  - build
  - test

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_TOOLS: "9477386"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # 1. Системные утилиты
  - apt-get update -yq && apt-get install -yq wget unzip

  # 2. Подготовка папок SDK
  - export ANDROID_HOME="$PWD/android-sdk-root"
  - mkdir -p "$ANDROID_HOME/cmdline-tools"

  # 3. Скачиваем архив
  - wget -qO sdk.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip"

  # 4. Распаковываем во временную папку, чтобы достать вложенный каталог
  - unzip -qq sdk.zip -d /tmp

  # 5. Перемещаем вложенный cmdline-tools в нужное место
  - mv /tmp/cmdline-tools "$ANDROID_HOME/cmdline-tools/latest"

  # 6. Удаляем временный архив и папки
  - rm -rf sdk.zip /tmp/cmdline-tools

  # 7. Вставляем sdkmanager в PATH
  - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

  # 8. Принимаем лицензии и ставим платформы
  - yes | sdkmanager --sdk_root="$ANDROID_HOME" --licenses >/dev/null
  - sdkmanager --sdk_root="$ANDROID_HOME" "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}"

  # 9. Делаем gradlew исполняемым
  - chmod +x ./gradlew



buildDebug:
  stage: build
  script:
    - echo "Собираем debug-APK…"
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unitTest:
  stage: test
  needs:
    - buildDebug
  script:
    - echo "Запускаем unit-тесты…"
    - ./gradlew testDebugUnitTest
