image: openjdk:17-jdk

variables:
  ANDROID_SDK_ROOT: "/sdk"
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"

stages:
  - build
  - test

before_script:
  - apt-get update -qq && apt-get install -y wget unzip
  - wget -O gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
  - unzip gradle.zip -d /opt/gradle
  - export PATH=$PATH:/opt/gradle/gradle-8.7/bin
  - set -x
  - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
  - unzip -v cmdline-tools.zip
  - unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
  - ls -l $ANDROID_SDK_ROOT/cmdline-tools
  - mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/tools
  - ls -l $ANDROID_SDK_ROOT/cmdline-tools/tools
  - yes | $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS"
  - ls -l $ANDROID_SDK_ROOT/platform-tools || true
  - export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS
  - yes | $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager --licenses


build:
  stage: build
  script:
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/
    paths:
      - app/build/reports/tests/testDebugUnitTest/
    expire_in: 1 week
