image: cimg/android:2025.04


stages:
  - lint
  - build
  - test
  - qa
  - report

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  SDK_ROOT: "$CI_PROJECT_DIR/android-sdk-root"

before_script:
  # 1) Принимаем лицензии и ставим платформы/инструменты
  - yes | sdkmanager --sdk_root="$SDK_ROOT" --install \
    "platform-tools" \
    "platforms;android-$ANDROID_COMPILE_SDK" \
    "build-tools;$ANDROID_BUILD_TOOLS"

### 1. Линтинг
lint:
  stage: lint
  script:
    - ./gradlew lintDebug
  artifacts:
    paths:
      - app/build/reports/lint-results.html

### 2. Сборка APK
build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk

### 3. JVM-тесты (unit + Robolectric)
unitTest:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/*.xml
    paths:
      - app/build/test-results/testDebugUnitTest/*.xml

### 4. QA-анализ (Detekt)
detekt:
  stage: qa
  script:
    - ./gradlew detekt
  artifacts:
    paths:
      - app/build/reports/detekt/

### 5. Отчёт по покрытию (Jacoco)
coverage:
  stage: report
  script:
    - ./gradlew jacocoTestReport
  artifacts:
    when: always
    paths:
      - app/build/reports/jacoco/
