[plugins]
android-application     = { id = "com.android.application", version = "8.1.2" }
kotlin-android         = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }
checkstyle             = { id = "checkstyle", version = "10.12.0" }
spotbugs               = { id = "com.github.spotbugs", version = "5.0.13" }
jacoco                 = { id = "jacoco", version = "0.8.10" }
dependency-check       = { id = "org.owasp.dependencycheck", version = "7.5.0" }
