[plugins]
android-application     = { id = "com.android.application", version = "8.1.4" }
kotlin-android         = { id = "org.jetbrains.kotlin.android", version = "2.0.21" }
checkstyle             = { id = "checkstyle", version = "10.12.0" }
spotbugs               = { id = "com.github.spotbugs", version = "5.0.13" }
jacoco                 = { id = "jacoco", version = "0.8.10" }
dependency-check       = { id = "org.owasp.dependencycheck", version = "7.5.0" }
[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }

